function(detect_msvc17)
    set(vsroot_pre "C:\\Program Files\\Microsoft Visual Studio\\2022\\")
    set(vsroot_edition)
    foreach(e Professional BuildTools Community Enterprise)
        if(IS_DIRECTORY "${vsroot_pre}${e}")
            set(vsroot_edition ${e})
            break()
        endif()
    endforeach()
    if(NOT vsroot_redition)
        return()
    endif()
    message(STATUS "VS Edition = ${vsroot_edition}")

    set(vsroot "${vsroot_pre}${vsroot_edition}")
    set(vcvars64 "${vsroot}\\VC\\Auxiliary\\Build\\vcvars64.bat")

    set(msvc17_vcvars64 "${vcvars64}" PARENT_SCOPE)
endfunction()
